// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bbksunwslrdqmlpwconi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJia3N1bndzbHJkcW1scHdjb25pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk5NjUyMDEsImV4cCI6MjA4NTU0MTIwMX0.zg6O6wifTJaRiusXtQ1rjJnTEHHYj75yTJnoqZg50tI";

// Supabase is configured with valid credentials
export const isSupabaseConfigured = true;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});